version: "3"
services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--configfile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - proxy
networks:
  proxy:
    external: true
